version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "org.jetbrains.kotlinx:*"
      ktor:
        patterns:
          - "io.ktor:*"
      jackson:
        patterns:
          - "com.fasterxml.jackson*:*"
      netty:
        patterns:
          - "io.netty:*"
      jooq:
        patterns:
          - "org.jooq:*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
