# suppress inspection "UnusedProperty" for whole file
salt=some-salt
key=some-key

test.db.url= jdbc:h2:~/test
test.db.user=sa
test.db.password=

local.db.url=jdbc:postgresql://localhost:5432/xiangqi
local.db.user=postgres
local.db.password=postgres

host=http://localhost:8080
minify=false
dockerized=false
ga=false
cookieConsentBanner=false
sendmails=false
caching=false

engines=true
enginesThreads=4
pikafishVersion=2023-03-05
fairyStockfishVersion=11.2
db=local
parseUserAgent=false

discord.token=
discord.suffix=

disabled.batches=FetchUserSessionGeographicDataBatch
